version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "authdb"
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "8080:8080"
    depends_on:
      - db
